garrysjh/NTUMart

.github/PULL_REQUEST_TEMPLATE.md
Add pull request template so that:
* Reviewers can have a better idea of what the PR is about.
* We can trace PR to JIRA ticket number.
=> [github flow] Add pull request template

README.md
=> DIP-26 update readme

server/src/main/java/com/ntumart/dipapp/api/controllers/ProfileUploadController.java, server/src/main/java/com/ntumart/dipapp/api/service/ProfUploadService.java
1. database entry naming
2. naming of endpoint
* https://garrysjh.atlassian.net/browse/DIP-38
=> [Fix] Naming

server/src/main/java/com/ntumart/dipapp/api/service/UserService.java
File directory creation no longer needed there
=> Update User Service.

DIPSHOP.sql
=> Update to dipshop.sql table

frontend/lib/body.dart, frontend/lib/pages/widgets/vertical_view_listings.dart
=> [fix] make listings views reusable

DIPSHOP.sql
Default Value for ProductLikes = 0
Shifted Unused old ideas below
=> Minor Update DIPSHOP.sql

DIPSHOP.sql
=> - [fix] enumeration in reviews sql table

server/src/main/java/com/ntumart/dipapp/api/controllers/ListingController.java, server/src/main/java/com/ntumart/dipapp/api/service/ListingService.java
Added a sortOrder option, allowing users to sort Ascending or Descending for name, price, date, category
=> Listings interests sort

server/application.properties, server/src/main/java/com/ntumart/dipapp/api/controllers/InterestController.java, server/src/main/java/com/ntumart/dipapp/api/repository/InterestRepository.java, server/src/main/java/com/ntumart/dipapp/models/Interest.java
=> Fixing userId problem in Interest

frontend/lib/models/productresponsemodel.dart, server/src/main/java/com/ntumart/dipapp/api/service/ProductResponseService.java, server/src/main/java/com/ntumart/dipapp/models/ProductResponse.java
=> added Id to productresponse

server/src/main/java/com/ntumart/dipapp/api/service/ProductService.java
Updated ProductService, Standardized the productImage filetype to .jpg
=> Upload ProductService

frontend/lib/settings.dart
=> settings page

server/src/main/resources/data.json
remove @ for telegram
add fullname
profile pic directory change
=> update : fullname + directory

server/src/main/java/com/ntumart/dipapp/api/repository/ListingRepository.java
=> Fixed interest

frontend/lib/body.dart, frontend/lib/settings.dart
Bless up 🙏   log out function 
@ptlinh1803 @W0ShiiSky @yongjin372k
=> [feature] log out (from settings)

frontend/lib/custominterests.dart, frontend/lib/selling.dart
=> checkbox in selling

server/src/main/java/com/ntumart/dipapp/api/controllers/ListingController.java, server/src/main/java/com/ntumart/dipapp/api/repository/ListingRepository.java
=> [fix] sql query

frontend/android/app/src/main/AndroidManifest.xml, frontend/ios/Podfile, frontend/ios/Runner/AppDelegate.swift, frontend/lib/homepage.dart, frontend/lib/pages/item.dart, frontend/pubspec.lock, frontend/pubspec.yaml
Default location: Hall 6
Preview:
@garrysjh 
=> added Google Map in item screen

frontend/lib/custominterests.dart, frontend/lib/models/interestmodel.dart, frontend/macos/Flutter/GeneratedPluginRegistrant.swift, frontend/pubspec.lock
=> Fix custom bug

frontend/lib/homepage.dart, frontend/macos/Flutter/GeneratedPluginRegistrant.swift, frontend/pubspec.lock
=> [fix] home-page

frontend/lib/pages/widgets/login/sign_up.dart
=> fix signup button

frontend/lib/category_button.dart, frontend/lib/homepage.dart, frontend/lib/showcategory.dart
=> link category page

frontend/assets/.gitignore
=> gitignore dialogflow file

frontend/lib/item_card.dart, frontend/lib/selling.dart, frontend/lib/settings.dart
=> fix ui issues

frontend/lib/homepage.dart
=> changes made by ariel

frontend/lib/ProductSearchBar.dart, frontend/lib/homepage.dart, frontend/lib/pages/widgets/taskbar.dart, frontend/lib/showallsearchbar.dart, server/src/main/java/com/ntumart/dipapp/api/controllers/ListingController.java, server/src/main/java/com/ntumart/dipapp/api/repository/ListingRepository.java, server/src/main/java/com/ntumart/dipapp/api/service/ListingService.java
=> [feature] search by search bar

frontend/lib/homepage.dart
=> [fix] merge issues

frontend/lib/showallsearchbar.dart, frontend/lib/showcategory.dart
=> [add] taskbars

frontend/lib/body.dart, frontend/lib/pages/profile.dart, server/src/main/java/com/ntumart/dipapp/api/controllers/ListingController.java, server/src/main/java/com/ntumart/dipapp/api/repository/ListingRepository.java, server/src/main/java/com/ntumart/dipapp/api/service/ListingService.java
Before the profile screen has no products now have
=> [fix] getProducts from server for profile

frontend/lib/item_card.dart
=> [fix] images distortion

frontend/lib/selling.dart, frontend/lib/settings.dart
=> [lint] add const and final

frontend/lib/homepage.dart
=> adjusted homepage

frontend/lib/body.dart, frontend/lib/pages/jwtTokenDecryptService.dart, frontend/lib/pages/profile.dart, server/src/main/java/com/ntumart/dipapp/api/repository/UserRepository.java, server/src/main/java/com/ntumart/dipapp/api/service/JwtTokenService.java
=> [fix] profile.dart

frontend/lib/homepage.dart
=> minor changes only
